name: Flutter Test and Release
on:
  push:
    branches:
      - master
      - develop

  workflow_dispatch:
jobs:
  flutter_test:
    name: Flutter Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Get dependencies
        run: flutter pub get
      - name: Run analyze
        run: flutter analyze
      - name: Run test cases
        run: flutter test
  build_appbundle:
    name: Flutter Release
    runs-on: windows-latest
    needs: [ flutter_test ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Get dependencies
        run: flutter pub get
      - name: Clean build
        run: flutter clean
      - name: Build APK
        run: flutter build apk --debug --split-per-abi
      - run: flutter build ios --no-codesign

      # Create iOS IPA
      - run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: 
           build/app/outputs/apk/debug/*.apk
           build/ios/iphoneos/app.ipa
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
